### ISSUE TITLE
Immutability

### ISSUE THREAD

**Issue by dantleech** [php-tui/php-tui#19]
Migrate widget classes to be immutable?

Widgets and shapes in Ratatui are mutable. What benefit would making them immutable bring?

## Caching

If the object ID changed, then the widget was mutated and needs to be re-rendererd?

This works until a point, and that point is when:

- The state is maintained outside of the object, which is the case with all stateful widgets and the `Position` value objects can be mutated too.

**Comment by dkarlovi** [comment]
If the ID changes, you re-render, but one common situation I'd expect to see is a few common IDs being used over and over (loops etc). Immutability would allow to have a cache of several IDs ready to go and evict them LFU style (or some combination of).

> Ratatui are mutable

Not sure that's relevant because it's quite possible they get to use some tricks PHP does not, you need to take your wins where you can get them. :)

**Comment by dantleech** [comment]
> Ratatui are mutable

it's not, just explaining why they're immutable now.

as mentioned above the problem is that currently state can be maintained outside of the object, so "has it changed" depends not only on if the widget was mutated, but also if the state was changed and there are different ways to handle that scenario. 

I had a go at switching to immutable objects yesterday, but got unstuck on this. It is very easy to switch, but I don't want to do so for the wrong reason at this point.

**Comment by dantleech** [comment]
closing this one for now ... immutability won't be a solution for "cache keys" as the rendered output may not be dependent on the state of the widget (e.g. data from external source) and the state may also be maintained in a separate object to the widget.
